# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esi', '0004_remove_unique_access_token'),
        ('eveonline', '0008_auto_20170902_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi.Token')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('date', models.DateTimeField()),
                ('_extra', models.TextField(default='{}', null=True)),
                ('first_party_id', models.IntegerField(null=True)),
                ('first_party_type', models.CharField(max_length=15, null=True)),
                ('reason', models.CharField(max_length=40, null=True)),
                ('ref_id', models.BigIntegerField(unique=True)),
                ('ref_type', models.CharField(max_length=100)),
                ('second_party_id', models.IntegerField(null=True)),
                ('second_party_type', models.CharField(max_length=15, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('tax_reciever_id', models.IntegerField(null=True)),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
            ],
            options={
                'permissions': (('view_alliance_finances', 'Can see finances for the entire alliance'), ('view_corp_finances', 'Can see finances for their own corp')),
            },
        ),
        migrations.CreateModel(
            name='TaxChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eveonline.EveCorporationInfo')),
            ],
        ),
    ]
