# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimer', '0002_auto_20170413_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimer',
            name='rzr_optimer_id',
            field=models.IntegerField(default=0),
        ),
    ]
