# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetactivitytracking', '0003_auto_20160906_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='FatLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
                'permissions': (('fat_statistics_corp', 'Can view corp statistics only'),),
            },
        ),
    ]
